version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: codebeutel
      POSTGRES_PASSWORD: codebeutel
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  api:
    image: codebeutel-api
    build:
      context: .
      dockerfile: ./build/Dockerfile-api
    ports:
      - 8081:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
